#!/usr/bin/perl

use strict;
use warnings;

use JSON;

my %next;

for my $c1 ('a' .. 'z') {
    for my $c2 ('a' .. 'z') {
        $next{$c1}{$c2} = 0;
    }
}

while (<>) {
    chomp;
    tr/A-Z/a-z/;
    s/[^a-z ]//g;

    my @words = split /\s/;
    for my $word (@words) {
        my @chars = split //, $word;

        my $state = '$';
        for my $c (@chars) {
            $next{$state}{$c}++;
            $state = $c;
        }
        $next{$state}{'$'}++;
    }
}

for my $c (keys %next) {
    my $count = 0.0;

    for my $v (keys %{ $next{$c} }) {
        $count += $next{$c}{$v};
    }

    for my $v (keys %{ $next{$c} }) {
        $next{$c}{$v} = ($next{$c}{$v} + 1) / ($count + 2);
    }
}

print "var markov=", encode_json(\%next), ";\n";
